// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: qrok/v1/tunnel.proto

package qrokv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TunnelService_AgentStream_FullMethodName  = "/qrok.v1.TunnelService/AgentStream"
	TunnelService_ListenStream_FullMethodName = "/qrok.v1.TunnelService/ListenStream"
)

// TunnelServiceClient is the client API for TunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TunnelService — транспорт туннеля между агентом/dev-клиентом и облаком.
// Аутентификация — токен в gRPC-metadata (authorization: Bearer <token>).
type TunnelServiceClient interface {
	// AgentStream: агент шлёт события со стейджинга, сервер подтверждает Ack'ами.
	// Агент коммитит оффсет в брокере только после получения Ack.
	AgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentStreamRequest, AgentStreamResponse], error)
	// ListenStream: dev-клиент объявляет подписку, сервер пушит события;
	// клиент отвечает DeliveryResult'ами о доставке на localhost.
	ListenStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ListenStreamRequest, ListenStreamResponse], error)
}

type tunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelServiceClient(cc grpc.ClientConnInterface) TunnelServiceClient {
	return &tunnelServiceClient{cc}
}

func (c *tunnelServiceClient) AgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentStreamRequest, AgentStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TunnelService_ServiceDesc.Streams[0], TunnelService_AgentStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentStreamRequest, AgentStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_AgentStreamClient = grpc.BidiStreamingClient[AgentStreamRequest, AgentStreamResponse]

func (c *tunnelServiceClient) ListenStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ListenStreamRequest, ListenStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TunnelService_ServiceDesc.Streams[1], TunnelService_ListenStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListenStreamRequest, ListenStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_ListenStreamClient = grpc.BidiStreamingClient[ListenStreamRequest, ListenStreamResponse]

// TunnelServiceServer is the server API for TunnelService service.
// All implementations must embed UnimplementedTunnelServiceServer
// for forward compatibility.
//
// TunnelService — транспорт туннеля между агентом/dev-клиентом и облаком.
// Аутентификация — токен в gRPC-metadata (authorization: Bearer <token>).
type TunnelServiceServer interface {
	// AgentStream: агент шлёт события со стейджинга, сервер подтверждает Ack'ами.
	// Агент коммитит оффсет в брокере только после получения Ack.
	AgentStream(grpc.BidiStreamingServer[AgentStreamRequest, AgentStreamResponse]) error
	// ListenStream: dev-клиент объявляет подписку, сервер пушит события;
	// клиент отвечает DeliveryResult'ами о доставке на localhost.
	ListenStream(grpc.BidiStreamingServer[ListenStreamRequest, ListenStreamResponse]) error
	mustEmbedUnimplementedTunnelServiceServer()
}

// UnimplementedTunnelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTunnelServiceServer struct{}

func (UnimplementedTunnelServiceServer) AgentStream(grpc.BidiStreamingServer[AgentStreamRequest, AgentStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method AgentStream not implemented")
}
func (UnimplementedTunnelServiceServer) ListenStream(grpc.BidiStreamingServer[ListenStreamRequest, ListenStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ListenStream not implemented")
}
func (UnimplementedTunnelServiceServer) mustEmbedUnimplementedTunnelServiceServer() {}
func (UnimplementedTunnelServiceServer) testEmbeddedByValue()                       {}

// UnsafeTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServiceServer will
// result in compilation errors.
type UnsafeTunnelServiceServer interface {
	mustEmbedUnimplementedTunnelServiceServer()
}

func RegisterTunnelServiceServer(s grpc.ServiceRegistrar, srv TunnelServiceServer) {
	// If the following call panics, it indicates UnimplementedTunnelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TunnelService_ServiceDesc, srv)
}

func _TunnelService_AgentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServiceServer).AgentStream(&grpc.GenericServerStream[AgentStreamRequest, AgentStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_AgentStreamServer = grpc.BidiStreamingServer[AgentStreamRequest, AgentStreamResponse]

func _TunnelService_ListenStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServiceServer).ListenStream(&grpc.GenericServerStream[ListenStreamRequest, ListenStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_ListenStreamServer = grpc.BidiStreamingServer[ListenStreamRequest, ListenStreamResponse]

// TunnelService_ServiceDesc is the grpc.ServiceDesc for TunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qrok.v1.TunnelService",
	HandlerType: (*TunnelServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AgentStream",
			Handler:       _TunnelService_AgentStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ListenStream",
			Handler:       _TunnelService_ListenStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "qrok/v1/tunnel.proto",
}
