// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qrok/v1/tunnel.proto

package qrokv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentStreamRequest_Hello
	//	*AgentStreamRequest_Event
	Msg           isAgentStreamRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStreamRequest) Reset() {
	*x = AgentStreamRequest{}
	mi := &file_qrok_v1_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStreamRequest) ProtoMessage() {}

func (x *AgentStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qrok_v1_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStreamRequest.ProtoReflect.Descriptor instead.
func (*AgentStreamRequest) Descriptor() ([]byte, []int) {
	return file_qrok_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *AgentStreamRequest) GetMsg() isAgentStreamRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentStreamRequest) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Msg.(*AgentStreamRequest_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentStreamRequest) GetEvent() *EventEnvelope {
	if x != nil {
		if x, ok := x.Msg.(*AgentStreamRequest_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isAgentStreamRequest_Msg interface {
	isAgentStreamRequest_Msg()
}

type AgentStreamRequest_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // первое сообщение стрима
}

type AgentStreamRequest_Event struct {
	Event *EventEnvelope `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*AgentStreamRequest_Hello) isAgentStreamRequest_Msg() {}

func (*AgentStreamRequest_Event) isAgentStreamRequest_Msg() {}

type AgentStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentStreamResponse_Ack
	//	*AgentStreamResponse_Goaway
	Msg           isAgentStreamResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStreamResponse) Reset() {
	*x = AgentStreamResponse{}
	mi := &file_qrok_v1_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStreamResponse) ProtoMessage() {}

func (x *AgentStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qrok_v1_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStreamResponse.ProtoReflect.Descriptor instead.
func (*AgentStreamResponse) Descriptor() ([]byte, []int) {
	return file_qrok_v1_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *AgentStreamResponse) GetMsg() isAgentStreamResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentStreamResponse) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*AgentStreamResponse_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *AgentStreamResponse) GetGoaway() *Goaway {
	if x != nil {
		if x, ok := x.Msg.(*AgentStreamResponse_Goaway); ok {
			return x.Goaway
		}
	}
	return nil
}

type isAgentStreamResponse_Msg interface {
	isAgentStreamResponse_Msg()
}

type AgentStreamResponse_Ack struct {
	Ack *Ack `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type AgentStreamResponse_Goaway struct {
	Goaway *Goaway `protobuf:"bytes,2,opt,name=goaway,proto3,oneof"`
}

func (*AgentStreamResponse_Ack) isAgentStreamResponse_Msg() {}

func (*AgentStreamResponse_Goaway) isAgentStreamResponse_Msg() {}

type ListenStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ListenStreamRequest_Subscribe
	//	*ListenStreamRequest_DeliveryResult
	Msg           isListenStreamRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenStreamRequest) Reset() {
	*x = ListenStreamRequest{}
	mi := &file_qrok_v1_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenStreamRequest) ProtoMessage() {}

func (x *ListenStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qrok_v1_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenStreamRequest.ProtoReflect.Descriptor instead.
func (*ListenStreamRequest) Descriptor() ([]byte, []int) {
	return file_qrok_v1_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *ListenStreamRequest) GetMsg() isListenStreamRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ListenStreamRequest) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Msg.(*ListenStreamRequest_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ListenStreamRequest) GetDeliveryResult() *DeliveryResult {
	if x != nil {
		if x, ok := x.Msg.(*ListenStreamRequest_DeliveryResult); ok {
			return x.DeliveryResult
		}
	}
	return nil
}

type isListenStreamRequest_Msg interface {
	isListenStreamRequest_Msg()
}

type ListenStreamRequest_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"` // первое сообщение стрима
}

type ListenStreamRequest_DeliveryResult struct {
	DeliveryResult *DeliveryResult `protobuf:"bytes,2,opt,name=delivery_result,json=deliveryResult,proto3,oneof"`
}

func (*ListenStreamRequest_Subscribe) isListenStreamRequest_Msg() {}

func (*ListenStreamRequest_DeliveryResult) isListenStreamRequest_Msg() {}

type ListenStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ListenStreamResponse_Event
	//	*ListenStreamResponse_Goaway
	Msg           isListenStreamResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenStreamResponse) Reset() {
	*x = ListenStreamResponse{}
	mi := &file_qrok_v1_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenStreamResponse) ProtoMessage() {}

func (x *ListenStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qrok_v1_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenStreamResponse.ProtoReflect.Descriptor instead.
func (*ListenStreamResponse) Descriptor() ([]byte, []int) {
	return file_qrok_v1_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *ListenStreamResponse) GetMsg() isListenStreamResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ListenStreamResponse) GetEvent() *EventEnvelope {
	if x != nil {
		if x, ok := x.Msg.(*ListenStreamResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ListenStreamResponse) GetGoaway() *Goaway {
	if x != nil {
		if x, ok := x.Msg.(*ListenStreamResponse_Goaway); ok {
			return x.Goaway
		}
	}
	return nil
}

type isListenStreamResponse_Msg interface {
	isListenStreamResponse_Msg()
}

type ListenStreamResponse_Event struct {
	Event *EventEnvelope `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type ListenStreamResponse_Goaway struct {
	Goaway *Goaway `protobuf:"bytes,2,opt,name=goaway,proto3,oneof"`
}

func (*ListenStreamResponse_Event) isListenStreamResponse_Msg() {}

func (*ListenStreamResponse_Goaway) isListenStreamResponse_Msg() {}

type AgentHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	SourceType    string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // kafka | rabbitmq
	Topics        []string               `protobuf:"bytes,4,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_qrok_v1_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_qrok_v1_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_qrok_v1_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *AgentHello) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *AgentHello) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"` // пусто = все топики туннеля
	HeaderFilters map[string]string      `protobuf:"bytes,3,rep,name=header_filters,json=headerFilters,proto3" json:"header_filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CatchUp       bool                   `protobuf:"varint,4,opt,name=catch_up,json=catchUp,proto3" json:"catch_up,omitempty"` // доставить накопленные offline-доставки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_qrok_v1_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_qrok_v1_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_qrok_v1_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *Subscribe) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *Subscribe) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Subscribe) GetHeaderFilters() map[string]string {
	if x != nil {
		return x.HeaderFilters
	}
	return nil
}

func (x *Subscribe) GetCatchUp() bool {
	if x != nil {
		return x.CatchUp
	}
	return false
}

// EventEnvelope — единица данных туннеля.
// Инвариант: заполнено ровно одно из payload / payload_ref
// (payload_ref используется при размере >= порога, по умолчанию 256 КБ).
type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // ULID, генерирует агент — ключ идемпотентности
	TunnelId      string                 `protobuf:"bytes,2,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // kafka | rabbitmq
	Topic         string                 `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Key           []byte                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadRef    string                 `protobuf:"bytes,8,opt,name=payload_ref,json=payloadRef,proto3" json:"payload_ref,omitempty"` // ключ объекта в object store
	Partition     int32                  `protobuf:"varint,9,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,10,opt,name=offset,proto3" json:"offset,omitempty"`
	BrokerTsMs    int64                  `protobuf:"varint,11,opt,name=broker_ts_ms,json=brokerTsMs,proto3" json:"broker_ts_ms,omitempty"`
	IsReplay      bool                   `protobuf:"varint,12,opt,name=is_replay,json=isReplay,proto3" json:"is_replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_qrok_v1_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_qrok_v1_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_qrok_v1_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *EventEnvelope) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *EventEnvelope) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EventEnvelope) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *EventEnvelope) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetPayloadRef() string {
	if x != nil {
		return x.PayloadRef
	}
	return ""
}

func (x *EventEnvelope) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *EventEnvelope) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *EventEnvelope) GetBrokerTsMs() int64 {
	if x != nil {
		return x.BrokerTsMs
	}
	return 0
}

func (x *EventEnvelope) GetIsReplay() bool {
	if x != nil {
		return x.IsReplay
	}
	return false
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_qrok_v1_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_qrok_v1_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_qrok_v1_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type DeliveryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,2,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP-код localhost'а или 0, если доставка не удалась
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryResult) Reset() {
	*x = DeliveryResult{}
	mi := &file_qrok_v1_tunnel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryResult) ProtoMessage() {}

func (x *DeliveryResult) ProtoReflect() protoreflect.Message {
	mi := &file_qrok_v1_tunnel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryResult.ProtoReflect.Descriptor instead.
func (*DeliveryResult) Descriptor() ([]byte, []int) {
	return file_qrok_v1_tunnel_proto_rawDescGZIP(), []int{8}
}

func (x *DeliveryResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeliveryResult) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *DeliveryResult) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeliveryResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeliveryResult) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

// Goaway — сигнал graceful drain: клиент должен переподключиться к другому инстансу.
type Goaway struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goaway) Reset() {
	*x = Goaway{}
	mi := &file_qrok_v1_tunnel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goaway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goaway) ProtoMessage() {}

func (x *Goaway) ProtoReflect() protoreflect.Message {
	mi := &file_qrok_v1_tunnel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goaway.ProtoReflect.Descriptor instead.
func (*Goaway) Descriptor() ([]byte, []int) {
	return file_qrok_v1_tunnel_proto_rawDescGZIP(), []int{9}
}

func (x *Goaway) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_qrok_v1_tunnel_proto protoreflect.FileDescriptor

const file_qrok_v1_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x14qrok/v1/tunnel.proto\x12\aqrok.v1\"x\n" +
	"\x12AgentStreamRequest\x12+\n" +
	"\x05hello\x18\x01 \x01(\v2\x13.qrok.v1.AgentHelloH\x00R\x05hello\x12.\n" +
	"\x05event\x18\x02 \x01(\v2\x16.qrok.v1.EventEnvelopeH\x00R\x05eventB\x05\n" +
	"\x03msg\"i\n" +
	"\x13AgentStreamResponse\x12 \n" +
	"\x03ack\x18\x01 \x01(\v2\f.qrok.v1.AckH\x00R\x03ack\x12)\n" +
	"\x06goaway\x18\x02 \x01(\v2\x0f.qrok.v1.GoawayH\x00R\x06goawayB\x05\n" +
	"\x03msg\"\x94\x01\n" +
	"\x13ListenStreamRequest\x122\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x12.qrok.v1.SubscribeH\x00R\tsubscribe\x12B\n" +
	"\x0fdelivery_result\x18\x02 \x01(\v2\x17.qrok.v1.DeliveryResultH\x00R\x0edeliveryResultB\x05\n" +
	"\x03msg\"x\n" +
	"\x14ListenStreamResponse\x12.\n" +
	"\x05event\x18\x01 \x01(\v2\x16.qrok.v1.EventEnvelopeH\x00R\x05event\x12)\n" +
	"\x06goaway\x18\x02 \x01(\v2\x0f.qrok.v1.GoawayH\x00R\x06goawayB\x05\n" +
	"\x03msg\"\x87\x01\n" +
	"\n" +
	"AgentHello\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x16\n" +
	"\x06topics\x18\x04 \x03(\tR\x06topics\"\xeb\x01\n" +
	"\tSubscribe\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\x12L\n" +
	"\x0eheader_filters\x18\x03 \x03(\v2%.qrok.v1.Subscribe.HeaderFiltersEntryR\rheaderFilters\x12\x19\n" +
	"\bcatch_up\x18\x04 \x01(\bR\acatchUp\x1a@\n" +
	"\x12HeaderFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x03\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\ttunnel_id\x18\x02 \x01(\tR\btunnelId\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12\x10\n" +
	"\x03key\x18\x05 \x01(\fR\x03key\x12=\n" +
	"\aheaders\x18\x06 \x03(\v2#.qrok.v1.EventEnvelope.HeadersEntryR\aheaders\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x1f\n" +
	"\vpayload_ref\x18\b \x01(\tR\n" +
	"payloadRef\x12\x1c\n" +
	"\tpartition\x18\t \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\n" +
	" \x01(\x03R\x06offset\x12 \n" +
	"\fbroker_ts_ms\x18\v \x01(\x03R\n" +
	"brokerTsMs\x12\x1b\n" +
	"\tis_replay\x18\f \x01(\bR\bisReplay\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x03Ack\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"\xa2\x01\n" +
	"\x0eDeliveryResult\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vdelivery_id\x18\x02 \x01(\tR\n" +
	"deliveryId\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\" \n" +
	"\x06Goaway\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason2\xae\x01\n" +
	"\rTunnelService\x12L\n" +
	"\vAgentStream\x12\x1b.qrok.v1.AgentStreamRequest\x1a\x1c.qrok.v1.AgentStreamResponse(\x010\x01\x12O\n" +
	"\fListenStream\x12\x1c.qrok.v1.ListenStreamRequest\x1a\x1d.qrok.v1.ListenStreamResponse(\x010\x01B$Z\"qrok/internal/proto/qrok/v1;qrokv1b\x06proto3"

var (
	file_qrok_v1_tunnel_proto_rawDescOnce sync.Once
	file_qrok_v1_tunnel_proto_rawDescData []byte
)

func file_qrok_v1_tunnel_proto_rawDescGZIP() []byte {
	file_qrok_v1_tunnel_proto_rawDescOnce.Do(func() {
		file_qrok_v1_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qrok_v1_tunnel_proto_rawDesc), len(file_qrok_v1_tunnel_proto_rawDesc)))
	})
	return file_qrok_v1_tunnel_proto_rawDescData
}

var file_qrok_v1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_qrok_v1_tunnel_proto_goTypes = []any{
	(*AgentStreamRequest)(nil),   // 0: qrok.v1.AgentStreamRequest
	(*AgentStreamResponse)(nil),  // 1: qrok.v1.AgentStreamResponse
	(*ListenStreamRequest)(nil),  // 2: qrok.v1.ListenStreamRequest
	(*ListenStreamResponse)(nil), // 3: qrok.v1.ListenStreamResponse
	(*AgentHello)(nil),           // 4: qrok.v1.AgentHello
	(*Subscribe)(nil),            // 5: qrok.v1.Subscribe
	(*EventEnvelope)(nil),        // 6: qrok.v1.EventEnvelope
	(*Ack)(nil),                  // 7: qrok.v1.Ack
	(*DeliveryResult)(nil),       // 8: qrok.v1.DeliveryResult
	(*Goaway)(nil),               // 9: qrok.v1.Goaway
	nil,                          // 10: qrok.v1.Subscribe.HeaderFiltersEntry
	nil,                          // 11: qrok.v1.EventEnvelope.HeadersEntry
}
var file_qrok_v1_tunnel_proto_depIdxs = []int32{
	4,  // 0: qrok.v1.AgentStreamRequest.hello:type_name -> qrok.v1.AgentHello
	6,  // 1: qrok.v1.AgentStreamRequest.event:type_name -> qrok.v1.EventEnvelope
	7,  // 2: qrok.v1.AgentStreamResponse.ack:type_name -> qrok.v1.Ack
	9,  // 3: qrok.v1.AgentStreamResponse.goaway:type_name -> qrok.v1.Goaway
	5,  // 4: qrok.v1.ListenStreamRequest.subscribe:type_name -> qrok.v1.Subscribe
	8,  // 5: qrok.v1.ListenStreamRequest.delivery_result:type_name -> qrok.v1.DeliveryResult
	6,  // 6: qrok.v1.ListenStreamResponse.event:type_name -> qrok.v1.EventEnvelope
	9,  // 7: qrok.v1.ListenStreamResponse.goaway:type_name -> qrok.v1.Goaway
	10, // 8: qrok.v1.Subscribe.header_filters:type_name -> qrok.v1.Subscribe.HeaderFiltersEntry
	11, // 9: qrok.v1.EventEnvelope.headers:type_name -> qrok.v1.EventEnvelope.HeadersEntry
	0,  // 10: qrok.v1.TunnelService.AgentStream:input_type -> qrok.v1.AgentStreamRequest
	2,  // 11: qrok.v1.TunnelService.ListenStream:input_type -> qrok.v1.ListenStreamRequest
	1,  // 12: qrok.v1.TunnelService.AgentStream:output_type -> qrok.v1.AgentStreamResponse
	3,  // 13: qrok.v1.TunnelService.ListenStream:output_type -> qrok.v1.ListenStreamResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_qrok_v1_tunnel_proto_init() }
func file_qrok_v1_tunnel_proto_init() {
	if File_qrok_v1_tunnel_proto != nil {
		return
	}
	file_qrok_v1_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentStreamRequest_Hello)(nil),
		(*AgentStreamRequest_Event)(nil),
	}
	file_qrok_v1_tunnel_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentStreamResponse_Ack)(nil),
		(*AgentStreamResponse_Goaway)(nil),
	}
	file_qrok_v1_tunnel_proto_msgTypes[2].OneofWrappers = []any{
		(*ListenStreamRequest_Subscribe)(nil),
		(*ListenStreamRequest_DeliveryResult)(nil),
	}
	file_qrok_v1_tunnel_proto_msgTypes[3].OneofWrappers = []any{
		(*ListenStreamResponse_Event)(nil),
		(*ListenStreamResponse_Goaway)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qrok_v1_tunnel_proto_rawDesc), len(file_qrok_v1_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qrok_v1_tunnel_proto_goTypes,
		DependencyIndexes: file_qrok_v1_tunnel_proto_depIdxs,
		MessageInfos:      file_qrok_v1_tunnel_proto_msgTypes,
	}.Build()
	File_qrok_v1_tunnel_proto = out.File
	file_qrok_v1_tunnel_proto_goTypes = nil
	file_qrok_v1_tunnel_proto_depIdxs = nil
}
